HamroKitab/Models/Books.cs
using HamroKitab.Data.Base;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace HamroKitab.Model
{
    public class Books: IEntityBase
    {
        [Key]
        public int Id { get; set; }
        public string? Name { get; set; }
        public string? Description { get; set; }
        public double Price { get; set; }
        public string? ImageUrl { get; set; }
        public DateTime PublishDate { get; set; }

        /*public int CategoryId { get; set; }
        [ForeignKey("CategoryId")]
        public Category Category { get; set; }

        public int AuthorId { get; set; }
        [ForeignKey("AuthorId")]
        public Author Author { get; set; }*/

        public int PublisherId { get; set; }
        [ForeignKey("PublisherId")]
        public Publisher? Publisher { get; set; }

        //relationships
        public List<Author_Books>? Author_Books { get; set; }
        public List<Category_Books>? Category_Books { get; set; }

    }
}

HamroKitab/Controllers/AuthorController.cs
using HamroKitab.Data;
using Microsoft.AspNetCore.Mvc;
using HamroKitab.Data.Services;
using HamroKitab.Model;

namespace HamroKitab.Controllers
{
    public class AuthorController : Controller
    {
        private readonly IAuthorService _service;
        public AuthorController(IAuthorService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var authors = await _service.GetAllAsync();
            return View(authors);
        }

        //Get: Author/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureUrl,Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }

            await _service.AddAsync(author);
            return RedirectToAction(nameof(Index));
        }

        //Get: Author/Details
        public async Task<IActionResult> Details(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");
            return View(authorDetails);
        }

        //Get: Author/Edit 
        public async Task<IActionResult> Edit(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");
            return View(authorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureUrl,Bio")] Author author)
        {
            if (!ModelState.IsValid)
            {
                return View(author);
            }

            await _service.UpdateAsync(id, author);
            return RedirectToAction(nameof(Index));
        }

        //Get: Author/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");
            return View(authorDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var authorDetails = await _service.GetByIdAsync(id);
            if (authorDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HamroKitab/Controllers/BooksController.cs
using HamroKitab.Data;
using HamroKitab.Data.Services;
using HamroKitab.Model;
using HamroKitab.Data.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace HamroKitab.Controllers
{
    public class BooksController : Controller
    {
        private readonly IBooksService _service;
        public BooksController(IBooksService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var allBooks= await _service.GetAllAsync(n => n.Publisher!);   
            return View(allBooks);
        }
        public async Task<IActionResult> Filter(string searchString)
        {
            var allBooks = await _service.GetAllAsync(n => n.Publisher!);

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allBooks.Where(n => string.Equals(n.Name, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allBooks);
        }

        //GET : Books/Details
        public async Task<IActionResult> Details(int id)
        {
            var bookDetail = await _service.GetBooksByIdAsync(id);
            return View(bookDetail);
        }

        //GET : Books/Create 
        public async Task<IActionResult> Create()
        {
            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers,"Id","Name");
            ViewBag.Author = new SelectList(bookDropdownsData.Author, "Id", "FullName");
            ViewBag.Category = new SelectList(bookDropdownsData.Category, "Id", "Name");

            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> Create(NewBookVM Book)
        {
            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
                ViewBag.Author = new SelectList(bookDropdownsData.Author, "Id", "FullName");
                ViewBag.Category = new SelectList(bookDropdownsData.Category, "Id", "Name");

                return View(Book);
            }
            await _service.AddNewBookAsync(Book);
            return RedirectToAction(nameof(Index));
        }
        //GET : Books/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var bookDetails = await _service.GetBooksByIdAsync(id);
            if (bookDetails == null) return View("NotFound");

            var response = new NewBookVM()
            {
                Id = bookDetails.Id,
                Name = bookDetails.Name,
                Description = bookDetails.Description,
                Price = bookDetails.Price,
                ImageUrl = bookDetails.ImageUrl,
                PublisherId = bookDetails.PublisherId,
                AuthorIds = bookDetails.Author_Books!.Select(n => n.AuthorId).ToList(),
                CategoryIds = bookDetails.Category_Books!.Select(n => n.CategoryId).ToList()
            };

            var bookDropdownsData = await _service.GetNewBookDropdownsValues();

            ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
            ViewBag.Author = new SelectList(bookDropdownsData.Author, "Id", "FullName");
            ViewBag.Category = new SelectList(bookDropdownsData.Category, "Id", "Name");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewBookVM Book)
        {
            if (id != Book.Id) return View("NotFound");

            if (!ModelState.IsValid)
            {
                var bookDropdownsData = await _service.GetNewBookDropdownsValues();

                ViewBag.Publishers = new SelectList(bookDropdownsData.Publishers, "Id", "Name");
                ViewBag.Author = new SelectList(bookDropdownsData.Author, "Id", "FullName");
                ViewBag.Category = new SelectList(bookDropdownsData.Category, "Id", "Name");

                return View(Book);
            }
            await _service.UpdateBookAsync(Book);
            return RedirectToAction(nameof(Index));
        }
    }
}

HamroKitab/Controllers/OrderController.cs
using HamroKitab.Data.Cart;
using HamroKitab.Data.Services;
using HamroKitab.Data.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace HamroKitab.Controllers
{
    public class OrderController : Controller
    {
        private readonly IBooksService _booksService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrderService _orderService;
        public OrderController(IBooksService booksService, ShoppingCart shoppingCart, IOrderService orderService)
        {
            _booksService = booksService;
            _shoppingCart = shoppingCart;
            _orderService = orderService;
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var order = await _orderService.GetOrdersByUserIdAndRoleAsync(userId,userRole);
            return View(order);
        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;

            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };

            return View(response);
        }

        public async Task<ActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _booksService.GetBooksByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _booksService.GetBooksByIdAsync(id);

            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));
        }
        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _orderService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();
            return View("OrderCompleted");
        }

    }
}

HamroKitab/Controllers/PublisherController.cs
using HamroKitab.Data;
using Microsoft.AspNetCore.Mvc;
using HamroKitab.Data.Services;
using HamroKitab.Model;

namespace HamroKitab.Controllers
{
    public class PublisherController : Controller
    {
        private readonly IPublisherService _service;
        public PublisherController(IPublisherService service)
        {
            _service = service;
        }
        public async Task<IActionResult> Index()
        {
            var publishers = await _service.GetAllAsync();
            return View(publishers);
        }

        //Get: Publisher/Create
        public IActionResult Create ()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create ([Bind("Logo,Name,Description")] Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            await _service.AddAsync(publisher);
            return RedirectToAction(nameof(Index));
        }

        //Get: Publisher/Details
        public async Task<IActionResult> Details(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null) return View("NotFound");
            return View(publisherDetails);
        }

        //Get: Publisher/Edit 
        public async Task<IActionResult> Edit(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null) return View("Not Found");
            return View(publisherDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,Logo,Name,Description")] Publisher publisher)
        {
            if (!ModelState.IsValid)
            {
                return View(publisher);
            }
            await _service.UpdateAsync(id, publisher);
            return RedirectToAction(nameof(Index));
        }

        //Get: Publisher/Delete
        public async Task<IActionResult> Delete(int id)
        {
            var publisherDetails = await _service.GetByIdAsync(id);
            if (publisherDetails == null) return View("Not Found");
            return View(publisherDetails);
        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("Not Found");

            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

HamroKitab/Views/Books/Create.cshtml
@model NewBookVM

@using HamroKitab.Data.ViewModels
 
@{
    ViewData["Title"] = "Create a new book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new book</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublishDate" class="control-label"></label>
                                <input asp-for="PublishDate" type="date" class="form-control" />
                                <span asp-validation-for="PublishDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control"  asp-items="ViewBag.Author" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryIds" class="control-label"></label>
                                <select asp-for="CategoryIds" class="form-control" asp-items="ViewBag.Category" multiple></select>
                                <span asp-validation-for="CategoryIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

HamroKitab/Views/Books/Details.cshtml
@model Books

@{
    ViewData["Title"] = "Book details";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageUrl" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Publisher: </b>
                            <a asp-controller="Publisher" asp-action="Details" asp-route-id="@Model.PublisherId">
                                @Model.Publisher!.Name
                            </a>
                        </p>

                        <p class="card-text">
                            <b>Categories: </b>

                            @foreach (var category in Model.Category_Books!)
                            {
                                <span class=" d-inline-block text-center p-1 text-light bg-primary rounded">
                                    @category.Category!.Name
                                </span>
                            }
                        </p>

                        <p class="card-text"><b>Publish Date: </b>@Model.PublishDate.ToString("dd MMM yy")</p>

                        @*<p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>*@

                        <p class="card-text">
                            <b>Authors: </b>
                            <hr />
                            <div class="row">
                                @foreach (var author in Model.Author_Books!)
                                {
                                    <div class="column text-center col-lg-3 col-sm-3 col-md-3" style="padding: 0">
                                        <img class="border-info rounded-circle" src="@author.Author!.ProfilePictureUrl" style="max-width: 150px" />
                                        <br />
                                        <a asp-controller="Author" asp-action="Details" asp-route-id="@author.AuthorId">
                                            @author.Author.FullName
                                        </a>
                                    </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white"
                               asp-controller="Order"
                               asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

HamroKitab/Views/Books/Edit.cshtml
@model NewBookVM

@using HamroKitab.Data.ViewModels
 
@{
    ViewData["Title"] = "Update a new book";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update a new book</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublishDate" class="control-label"></label>
                                <input asp-for="PublishDate" type="date" class="form-control" />
                                <span asp-validation-for="PublishDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageUrl" class="control-label"></label>
                                <input asp-for="ImageUrl" class="form-control" />
                                <span asp-validation-for="ImageUrl" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label"></label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.Publishers"></select>
                                <span asp-validation-for="PublisherId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="AuthorIds" class="control-label"></label>
                                <select asp-for="AuthorIds" class="form-control"  asp-items="ViewBag.Author" multiple></select>
                                <span asp-validation-for="AuthorIds" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="CategoryIds" class="control-label"></label>
                                <select asp-for="CategoryIds" class="form-control" asp-items="ViewBag.Category" multiple></select>
                                <span asp-validation-for="CategoryIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100%" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{ 
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageUrl").val();
        })
        $("#ImageUrl").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

HamroKitab/Views/Books/Index.cshtml
@model IEnumerable<Books>

@{
    ViewData["Title"] = "List of Books";
}

<div class="row">
    @foreach (var item in Model)
    {
        <div class="col-md-4 col-xs-6 border-primary mb-3">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row g-0">
                    <div class="col-md-12">
                        <div class="card-header text-white bg-info">
                            <p class="card-text">
                                <h5 class="card-title">
                                    @item.Name
                                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                    {
                                        <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                    }
                                </h5>
                            </p>
                        </div>
                    </div>
                    <div class="col-md-6 ">
                        <img src="@item.ImageUrl" width="100%" alt="@item.Name">
                    </div>
                    <div class="col-md-6">
                        <div class="card-body">
                            <p class="card-text">@item.Description</p>
                            <p class="card-text"><b>Publisher: </b>@item.Publisher!.Name</p>
                            <p class="card-text"><b>Publish Date: </b>@item.PublishDate.ToString("dd MMM yy")</p>
                        </div>
                    </div>
                    <div class="col-md-12">
                        <div class="card-footer ">
                            <p class="card-text">
                                <a class="btn btn-outline-primary float-right" asp-action="Details" asp-route-id="@item.Id">
                                    <i class="bi bi-eye-fill"></i> Show Details
                                </a>
                                <a class="btn btn-success text-white"
                               asp-controller="Order"
                               asp-action="AddItemToShoppingCart"
                               asp-route-id="@item.Id">
                                    <i class="bi bi-cart-plus"></i> Add to Cart (Price @item.Price.ToString("c"))
                                </a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

@await Html.PartialAsync("_CreateItem", "Books") 